version: '3'

services:
  kimai:
    image: maestroalubia/kimai
    ports:
      - ${EXTERNAL_PORT:-127.0.0.1:8080}:80
    restart: always
    environment:
      - KIMAI_REMOVE_INSTALLATION=0 # or 1
      # See http://www.kimai.org/documentation/administrator/authenticator.html
      - KIMAI_AUTHENTICATOR= # ldap, ldapadvanced
    volumes:
      - ./autoconf.php:/var/www/html/includes/autoconf.php
      - ./auth.php:/var/www/html/includes/auth.php
  db:
    image: mariadb
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimai
      - MYSQL_PASSWORD=kimai
      - MYSQL_ROOT_PASSWORD=fKc8dlZqhNOucISGiZA6
    volumes:
      - ${DB_VOLUME:-./kimai-database}:/var/lib/mysql
    restart: always

